### ISSUE TITLE
Test fail to compile with GHC 9 + TypeApplications

### ISSUE THREAD

**Issue by phijor** [hapytex/levenshtein#9]
When using GHC 9 to compile this package (as `nix` does currently), the tests fail to type check with a rather obscure error:

```
test/Data/Foldable/LevenshteinSpec.hs:18:117: error:
    Variable not in scope:
      (@) :: ([a29] -> [a29] -> Bool) -> t29 -> prop29
   |
18 |   it "lowerbound string difference" (quickCheckWith stdArgs { maxSuccess = ntimes } (property (lowerBoundLengthDiff @ Int)))
   |                                                                                                                     ^

test/Data/Foldable/LevenshteinSpec.hs:18:119: error:
    Data constructor not in scope: Int
   |
18 |   it "lowerbound string difference" (quickCheckWith stdArgs { maxSuccess = ntimes } (property (lowerBoundLengthDiff @ Int)))
   |
```

This seems to be caused by the [whitespace-sensitive parsing](https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.0#whitespace-sensitive-and-) of certain operators, including `(@)` from the language extension `-XTypeApplications`.

To fix this, I propose changing occurences of `@ Foo` to `@Foo` everywhere in `test/Data/Foldable/LevenshteinSpec.hs`.

**Comment by KommuSoft** [comment]
Thanks. Yes, if I recall correctly they slightly changed the grammar such that the `@` now no longer can have spaces (it is probably not really a Haskell operator, but more a language operator). I rewrote this with:
```
sed -i -E 's/@\s+/@/g' **.hs
```
and will publish this as 0.2.1.0.

Thanks!
